// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: bitswap/network/sphinx/pb/keyrecord.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyRecord is the payload of a signed libp2p Envelope announcing a peer's
// Sphinx NIKE public key. It is distributed via the /sphinx/keys protocol.
// It is NOT attached to the libp2p PeerRecord: it is a separate Envelope
// type with its own domain and codec, so vanilla peers ignore it and its
// lifecycle is decoupled from address churn.
type KeyRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Marshalled peer ID of the key owner. Bound into the signature via the
	// enclosing Envelope; on consume we check it against the sending peer.
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Raw X25519 public key bytes (NIKE scheme key material).
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Monotonic sequence number, derived from the creation timestamp in
	// UNIX nanoseconds. A newer record MUST carry a higher seq.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Absolute expiry, UNIX nanoseconds. After this instant the record is
	// evicted from the key store and the associated replay-filter epoch ends.
	ExpiryUnixNano int64 `protobuf:"varint,4,opt,name=expiry_unix_nano,json=expiryUnixNano,proto3" json:"expiry_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyRecord) Reset() {
	*x = KeyRecord{}
	mi := &file_bitswap_network_sphinx_pb_keyrecord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRecord) ProtoMessage() {}

func (x *KeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_bitswap_network_sphinx_pb_keyrecord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRecord.ProtoReflect.Descriptor instead.
func (*KeyRecord) Descriptor() ([]byte, []int) {
	return file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescGZIP(), []int{0}
}

func (x *KeyRecord) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *KeyRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KeyRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *KeyRecord) GetExpiryUnixNano() int64 {
	if x != nil {
		return x.ExpiryUnixNano
	}
	return 0
}

var File_bitswap_network_sphinx_pb_keyrecord_proto protoreflect.FileDescriptor

var file_bitswap_network_sphinx_pb_keyrecord_proto_rawDesc = []byte{
	0x0a, 0x29, 0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2f, 0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2f, 0x70, 0x62, 0x2f, 0x6b, 0x65, 0x79, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x70, 0x68,
	0x69, 0x6e, 0x78, 0x2e, 0x70, 0x62, 0x22, 0x7f, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x28, 0x0a,
	0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x61, 0x6e,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x55,
	0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x70, 0x66, 0x73, 0x2f, 0x62, 0x6f, 0x78, 0x6f, 0x2f,
	0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescOnce sync.Once
	file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescData = file_bitswap_network_sphinx_pb_keyrecord_proto_rawDesc
)

func file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescGZIP() []byte {
	file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescOnce.Do(func() {
		file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescData = protoimpl.X.CompressGZIP(file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescData)
	})
	return file_bitswap_network_sphinx_pb_keyrecord_proto_rawDescData
}

var file_bitswap_network_sphinx_pb_keyrecord_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bitswap_network_sphinx_pb_keyrecord_proto_goTypes = []any{
	(*KeyRecord)(nil), // 0: sphinx.pb.KeyRecord
}
var file_bitswap_network_sphinx_pb_keyrecord_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bitswap_network_sphinx_pb_keyrecord_proto_init() }
func file_bitswap_network_sphinx_pb_keyrecord_proto_init() {
	if File_bitswap_network_sphinx_pb_keyrecord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bitswap_network_sphinx_pb_keyrecord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bitswap_network_sphinx_pb_keyrecord_proto_goTypes,
		DependencyIndexes: file_bitswap_network_sphinx_pb_keyrecord_proto_depIdxs,
		MessageInfos:      file_bitswap_network_sphinx_pb_keyrecord_proto_msgTypes,
	}.Build()
	File_bitswap_network_sphinx_pb_keyrecord_proto = out.File
	file_bitswap_network_sphinx_pb_keyrecord_proto_rawDesc = nil
	file_bitswap_network_sphinx_pb_keyrecord_proto_goTypes = nil
	file_bitswap_network_sphinx_pb_keyrecord_proto_depIdxs = nil
}
